### PR TITLE
fix: swap parcel for rollup

### PR DESCRIPTION
**Pull request by grumbaut**
This change fixes bundle file errors caused by unresolved `require('./util')` calls.

### CODE REVIEW

**Comment by sh0ji** [comment]
@grumbaut, I had some local changes that I apparently never pushed. The conflicts are just build artifacts. Could you rebase, run `yarn build`, and then push the updated build?

**Comment by grumbaut** [comment]
@sh0ji, I've rebased these changes and pushed everything to my fork. I kept your separate `build:node` and `build:browser` scripts by using different Rollup config files.

**Comment by sh0ji** [comment]
This still needs rollup-plugin-babel since the source is using some newer ES features like destructuring and rest/spread.

**Comment by grumbaut** [comment]
Added the plugin in. Is it the best practice for all NPM packages to include transpiled code?

**Comment by sh0ji** [comment]
Yes, if you want to write modern JS and still have wide support, it's best to supply a compiled version.

**Comment by sh0ji** [comment]
Perfect, merging!

**Pull request merged**
